### ISSUE TITLE
Exception when trying to use borg with llfuse 0.42.1

### ISSUE THREAD

**Issue by sigpipe** [borgbackup/borg#633]
It appears that the llfuse API for llfuse.main() has changed.  borg currently uses llfuse.main(single=True), and the new API call no longer accepts the _single_ keyword argument.  Instead, it appears that specifying _workers=1_ will mimic the old behavior.  See https://pythonhosted.org/llfuse/fuse_api.html#llfuse.main

> using builtin fallback logging configuration
> Remote: using builtin fallback logging configuration
> Mounting filesystem
> Initializing llfuse
> Calling fuse_mount
> Calling fuse_lowlevel_new
> Calling fuse_session_add_chan
> Calling fuse_session_remove_chan
> Calling fuse_session_destroy
> Calling fuse_unmount
> Local Exception.
> Traceback (most recent call last):
>   File "/data/borg-env/lib/python3.4/site-packages/borg/archiver.py", line 1261, in main
>     exit_code = archiver.run(args)
>   File "/data/borg-env/lib/python3.4/site-packages/borg/archiver.py", line 1215, in run
>     return args.func(args)
>   File "/data/borg-env/lib/python3.4/site-packages/borg/archiver.py", line 385, in do_mount
>     operations.mount(args.mountpoint, args.options, args.foreground)
>   File "/data/borg-env/lib/python3.4/site-packages/borg/fuse.py", line 238, in mount
>     llfuse.main(single=True)
>   File "src/fuse_api.pxi", line 273, in llfuse.main (src/llfuse.c:34380)
> TypeError: main() got an unexpected keyword argument 'single'
> 
> Platform: Linux xyz 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64
> Linux: Ubuntu 15.10 wily  LibC: glibc 2.9
> Python: CPython 3.4.3+

**Comment by ThomasWaldmann** [comment]
In the Vagrantfile we have llfuse<0.41, because 0.41.1 had all sorts of issues, not just what you described above.

**Comment by ThomasWaldmann** [comment]
https://bitbucket.org/nikratio/python-llfuse/issues/79/compatbility-breakage-of-main-in-042

**Comment by ThomasWaldmann** [comment]
Even when fixing the main() parameter issue, borg does not work with llfuse >= 0.42.

**Comment by ThomasWaldmann** [comment]
I added a version dependency and some comments to setup.py and requirements.d/fuse.txt, requiring llfuse < 0.41 - this will usually pull in the 0.40 version which is proven to work and disallows 0.42 (which does not work) and 0.41 (not tested enough, might work).

I'll open a separate ticket about making our code compatible with multiple llfuse versions / APIs.
