### ISSUE TITLE
2.0.0b3: AttributeError: 'borg.item.Item' object has no attribute '_dict'

### ISSUE THREAD

**Issue by pgerber** [borgbackup/borg#7077]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

In command name.

#### Operating system (distribution) and version.

Debian 11 on Qubes OS 4.1

#### Hardware / network configuration, and filesystems used.

Notebook, local repo, BTRFS

#### How much data is handled by borg?

106 GiB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
user@tmp-borg:~$ borg-1.2.2 check --verify stella

user@tmp-borg:~$ borg-2.0.0b3 rcreate -e repokey-blake2-chacha20-poly1305 --other-repo stella --repo stella_new

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

user@tmp-borg:~$ borg-2.0.0b3 transfer --other-repo stella --repo stella_new --upgrader=From12To20
vm:debian-11:root:1650914346-back: copying archive to destination repo...
Local Exception
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 594, in main
  File "borg/archiver/__init__.py", line 522, in run
  File "borg/archiver/_common.py", line 223, in wrapper
  File "borg/archiver/_common.py", line 155, in wrapper
  File "borg/archiver/transfer_cmd.py", line 100, in do_transfer
  File "borg/upgrade.py", line 80, in upgrade_item
AttributeError: 'borg.item.Item' object has no attribute '_dict'

Platform: Linux tmp-borg 5.19.9-1.fc32.qubes.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 16 14:54:56 CEST 2022 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b3  Python: CPython 3.9.14 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 2844  CWD: /home/user
sys.argv: ['borg-2.0.0b3', 'transfer', '--other-repo', 'stella', '--repo', 'stella_new', '--upgrader=From12To20']
SSH_ORIGINAL_COMMAND: None
```

This still worked with v2.0.0b2:

```
user@tmp-borg:~$ borg-2.0.0b2 rcreate -e repokey-blake2-chacha20-poly1305 --other-repo stella --repo stella_new

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

user@tmp-borg:~$ borg-2.0.0b2 transfer --other-repo stella --repo stella_new --upgrader=From12To20
vm:debian-11:root:1650914346-back: copying archive to destination repo...
vm:debian-11:root:1650914346-back: finished. transfer_size: 7.27 GB present_size: 3.47 GB
…
```

**Comment by infectormp** [comment]
there is no command `rcreate`, right name is `recreate `

**Comment by pgerber** [comment]
@infectormp, there will be in Borg 2 with some other r(epository) commands.

https://borgbackup.readthedocs.io/en/2.0.0b3/usage/rcreate.html

**Comment by infectormp** [comment]
eh, sorry I overlooked version.

**Comment by infectormp** [comment]
maybe related to https://github.com/borgbackup/borg/issues/7072

**Comment by ThomasWaldmann** [comment]
I can reproduce, this was caused by the cython code refactor / cleanup, #5763, which made `._dict` inaccessible from python.
