### ISSUE TITLE
borgbackup fails to build with Python 3.10: Avoid using PyObject_AsCharBuffer(), PyObject_AsReadBuffer() and PyObject_AsWriteBuffer()

### ISSUE THREAD

**Issue by FelixSchwarz** [borgbackup/borg#5683]
downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1927146

borgbackup fails to build with Python 3.10.0a5.

    src/borg/algorithms/msgpack/_unpacker.cpp:2332:17: error: "PyObject_AsReadBuffer" was not declared in this scope; did you mean "PyObject_GetBuffer"?
    2332 |     __pyx_t_2 = PyObject_AsReadBuffer(__pyx_v_obj, ((void const **)__pyx_v_buf), __pyx_v_buffer_len); if (unlikely(__pyx_t_2 == ((int)-1))) __PYX_ERR(0, 152, __pyx_L1_error)
         |                 ^~~~~~~~~~~~~~~~~~~~~
         |                 PyObject_GetBuffer
    error: command '/usr/bin/gcc' failed with exit code 1

https://docs.python.org/3.10/whatsnew/changelog.html#id16

> bpo-41103: PyObject_AsCharBuffer(), PyObject_AsReadBuffer(), PyObject_CheckReadBuffer(), and PyObject_AsWriteBuffer() are removed. Please migrate to new buffer protocol; PyObject_GetBuffer() and PyBuffer_Release().

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.10/fedora-rawhide-x86_64/01951890-borgbackup/

For all our attempts to build borgbackup with Python 3.10, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.10/package/borgbackup/

Testing and mass rebuild of packages is happening in copr. You can follow these instructions to test locally in mock if your package builds with Python 3.10:
https://copr.fedorainfracloud.org/coprs/g/python/python3.10/

**Comment by ThomasWaldmann** [comment]
this is an issue with the bundled msgpack code, which can be used, but there is not obligation to use it, you can also use a compatible msgpack externally, see hints in `setup.py`.

when looking at msgpack, it could be that one needs C code generated by a newer Cython, that generates py310 compatible code.

**Comment by FelixSchwarz** [comment]
> this is an issue with the bundled msgpack code, which can be used, but there is not obligation to use it, you can also use a compatible msgpack externally, see hints in setup.py.

Unfortunately using the system-provided msgpack is not an option for Fedora as that version is msgpack 1.0.0.

> when looking at msgpack, it could be that one needs C code generated by a newer Cython, that generates py310 compatible code.

Also we are removing all pre-cythonized `.cpp` files before building so everything is regenerated with Fedora's Cython.

Looking at `_unpacker.pyx` I see an explicit reference to `PyObject_AsReadBuffer` in `get_data_from_buffer()` when using the "old protocol". I think this was fixed in upstream version 1.0 with [commit 9ae43709](https://github.com/msgpack/msgpack-python/commit/9ae43709e42092c7f6a4e990d696d9005fa1623d).

So I backported that commit for Fedora 35 (and I'd like to drop that as soon as borgbackup 1.2 is released) and borg's test suite still passes: [borgbackup-msgpack-drop-old-buffer-protocol.patch.txt](https://github.com/borgbackup/borg/files/5961849/borgbackup-msgpack-drop-old-buffer-protocol.patch.txt)

Feel free to close the ticket if supporting the vendored msgpack with Python 3.10 is too time consuming. It might be easier to do for Fedora as we do not have to bother with backwards compatibility if we apply the patch only for Fedora rawhide (F35+). If I'm reading the [CPython documentation about the old buffer protocol](https://docs.python.org/3/c-api/objbuffer.html) correctly it is deprecated since Python 3.0.

**Comment by ThomasWaldmann** [comment]
Guess if that old stuff is deprecated for that long (since py30), the new method should be working good enough for all python versions borg 1.1.x supports.

I've just noticed that we do not have the C code committed to the repo, so a PR for this would likely be just the same as the patch for fedora, so we could just try that. Guess Gentoo, ArchLinux and similiar will run into same issue.

Also, guess we should use a new version number (0.5.7, that was never used for official msgpack) for this patched msgpack, so it is clear that it is not the official release.

@FelixSchwarz can you do such a PR please?

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann i would recommend a local version tag added if possible (append `+something`)

**Comment by ThomasWaldmann** [comment]
fixed by #5684 in 1.1-maint.

master uses latest msgpack, so only a partial forward-port needed for there.
