### ISSUE TITLE
Borg 1.4 Fix for python3.13: ImportError: cannot import name 'pbkdf2_hmac'

### ISSUE THREAD

**Issue by dagelf** [borgbackup/borg#8691]
Installing borg 1.4 on a machine with Python 3.13 gives this:

$ borg -V
Traceback (most recent call last):
  File "/home/coenraad/.venv/lib/python3.13/site-packages/borg/archiver.py", line 38, in <module>
    from .archive import Archive, ArchiveChecker, ArchiveRecreater, Statistics, is_special
  File "/home/coenraad/.venv/lib/python3.13/site-packages/borg/archive.py", line 24, in <module>
    from .cache import ChunkListEntry
  File "/home/coenraad/.venv/lib/python3.13/site-packages/borg/cache.py", line 31, in <module>
    from .crypto.key import PlaintextKey
  File "/home/coenraad/.venv/lib/python3.13/site-packages/borg/crypto/key.py", line 10, in <module>
    from hashlib import sha256, sha512, pbkdf2_hmac
ImportError: cannot import name 'pbkdf2_hmac' from 'hashlib' (/usr/lib/python3.13/hashlib.py)

$ sudo pacman -Ql borg|grep crypto/key.py
borg /usr/lib/python3.13/site-packages/borg/crypto/key.py
$ grep pbkdf /usr/lib/python3.13/site-packages/borg/crypto/key.py
from _hashlib import pbkdf2_hmac

The fix is to move the `pbkdf2_hmac` to a new line importing from _hashlib. 

```
import sys

if sys.version_info >= (3, 13):
    from _hashlib import pbkdf2_hmac
else:
    from hashlib import pbkdf2_hmac
```

**Comment by dagelf** [comment]
Sorry about posting this here but I can't find the old/a borgbackup repo, without spending an hour or more now looking at where the various distros pull it from.

**Comment by ThomasWaldmann** [comment]
This is the correct repo and issue tracker, the 1.4 code is in 1.4-maint branch.

But that "fix" looks very suspicious.

Considering that this function should be in hashlib (as documented there: https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac ), I would suspect that your Python maybe was not built correctly with OpenSSL?

**Comment by ThomasWaldmann** [comment]
@dagelf ping?

**Comment by dagelf** [comment]
Apparently the function moved to a Python internal in 3.13 - the following
is listed in the Changelog:
*added runtime detection for BLAKE2, SHA3, and truncated SHA512 in hashlib
(gh-117233).*

I was just trying to get it working on Arch which uses Python 3.13, and
pacman -S borgbackup installs 1.4.0 whcih errors without this change.

**Comment by ThomasWaldmann** [comment]
Maybe just try that on a Python 3.13 interpreter prompt:
```
from hashlib import pbkdf2_hmac
```

As that is a documented api call, it should work **IF your Python was built with OpenSSL support (that's documented there also).**

**Comment by dagelf** [comment]
Super weird, it now works, so this isn't necessary. I'm not too familiar with Python's internals, but maybe the import failed due to an outdated OpenSSL library, and I didn't notice that the library was also updated in between me making the change. For interests' sake, will confirm when I'm back at that server (if I remember) which will be offline for the next two weeks.
